
#ifndef _EXPLORER_H
#define _EXPLORER_H 1

#define FILE_DEVICE_EXPLORER	0x8000


#define EXPLORER_IOCTL_BASE	0x800

#define CTL_CODE_EXPLORER(i) CTL_CODE(FILE_DEVICE_EXPLORER, EXPLORER_IOCTL_BASE+i, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_EXPLORER_HELLO	CTL_CODE_EXPLORER(0)
#define IOCTL_EXPLORER_TEST	CTL_CODE_EXPLORER(1)

#define EXPLORER_WIN32_DEVICE_NAME_A	"\\\\.\\explorer"
#define EXPLORER_WIN32_DEVICE_NAME_W	L"\\\\.\\explorer"
#define EXPLORER_DEVICE_NAME_A			"\\Device\\explorer"
#define EXPLORER_DEVICE_NAME_W			L"\\Device\\explorer"
#define EXPLORER_DOS_DEVICE_NAME_A		"\\DosDevices\\explorer"
#define EXPLORER_DOS_DEVICE_NAME_W		L"\\DosDevices\\explorer"

#ifdef _UNICODE
#define EXPLORER_WIN32_DEVICE_NAME EXPLORER_WIN32_DEVICE_NAME_W
#define EXPLORER_DEVICE_NAME		EXPLORER_DEVICE_NAME_W
#define EXPLORER_DOS_DEVICE_NAME	EXPLORER_DOS_DEVICE_NAME_W
#else
#define EXPLORER_WIN32_DEVICE_NAME EXPLORER_WIN32_DEVICE_NAME_A
#define EXPLORER_DEVICE_NAME		EXPLORER_DEVICE_NAME_A
#define EXPLORER_DOS_DEVICE_NAME	EXPLORER_DOS_DEVICE_NAME_A
#endif

#endif